#Task2: Try Linear regression on same prediction data using Tensorflow

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70],[73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70]], dtype='float64')

targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], 
                    [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float64')

In [3]:
inputs = tf.Variable(inputs)
targets = tf.Variable(targets)
print("targets :\n",targets)

targets :
 <tf.Variable 'Variable:0' shape=(15, 2) dtype=float64, numpy=
array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]])>


In [4]:
v = np.random.rand(3,2)
r = np.random.randn(2)
v = tf.Variable(v)
r = tf.Variable(r)

print(v)
print("\n",r)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
array([[0.70969651, 0.40972951],
       [0.84011952, 0.30345144],
       [0.61947075, 0.91814642]])>

 <tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([-1.76834093,  0.85829184])>


In [5]:
def model(s):
    return s @ v + r

In [6]:
prediction = model(inputs)
print(prediction)

tf.Tensor(
[[132.96475416  90.58008845]
 [176.3906869  123.60877462]
 [208.48057414 130.41974408]
 [129.66626012  89.67053134]
 [171.21514425 122.53121536]
 [132.96475416  90.58008845]
 [176.3906869  123.60877462]
 [208.48057414 130.41974408]
 [129.66626012  89.67053134]
 [171.21514425 122.53121536]
 [132.96475416  90.58008845]
 [176.3906869  123.60877462]
 [208.48057414 130.41974408]
 [129.66626012  89.67053134]
 [171.21514425 122.53121536]], shape=(15, 2), dtype=float64)


In [7]:
def mse(t1,t2):
    return tf.reduce_mean(tf.square(t1 - t2))
print(mse(prediction,targets))

tf.Tensor(4300.306795520153, shape=(), dtype=float64)


In [8]:
epochs = 40
for epoch_count in range(epochs):
    
    with tf.GradientTape(persistent=True) as t:
        current_loss = mse(targets, model(inputs))

    v1 = t.gradient(current_loss,v)
    r1 = t.gradient(current_loss,r)

    v.assign_sub(1e-4 * v1)
    r.assign_sub(1e-4 * r1)
        
    print(f" \n Epoch count: {epoch_count} \n Loss value: {current_loss.numpy()}")


 
 Epoch count: 0 
 Loss value: 4300.306795520153
 
 Epoch count: 1 
 Loss value: 2806.9425946954266
 
 Epoch count: 2 
 Loss value: 1858.576171908858
 
 Epoch count: 3 
 Loss value: 1252.887579100573
 
 Epoch count: 4 
 Loss value: 863.0941894102717
 
 Epoch count: 5 
 Loss value: 609.6952342588697
 
 Epoch count: 6 
 Loss value: 442.79210836530234
 
 Epoch count: 7 
 Loss value: 331.02522409216897
 
 Epoch count: 8 
 Loss value: 254.65049586081642
 
 Epoch count: 9 
 Loss value: 201.20586177937759
 
 Epoch count: 10 
 Loss value: 162.7983864647361
 
 Epoch count: 11 
 Loss value: 134.40542484632485
 
 Epoch count: 12 
 Loss value: 112.81038189889067
 
 Epoch count: 13 
 Loss value: 95.93565153566306
 
 Epoch count: 14 
 Loss value: 82.42418579038434
 
 Epoch count: 15 
 Loss value: 71.37674350163184
 
 Epoch count: 16 
 Loss value: 62.18665200769508
 
 Epoch count: 17 
 Loss value: 54.435678342603104
 
 Epoch count: 18 
 Loss value: 47.828223071892154
 
 Epoch count: 19 
 Loss value: